# Generated by Django 4.2.7 on 2023-11-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikipediaArticle',
            fields=[
                ('pageid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ns', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('index', models.IntegerField()),
                ('coordinates_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('coordinates_lon', models.DecimalField(decimal_places=6, max_digits=10)),
                ('thumbnail', models.URLField()),
                ('pageimage', models.URLField(default='')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
