# Generated by Django 4.2.7 on 2023-11-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipediaarticle',
            name='pageimage',
            field=models.URLField(default='', null=True),
        ),
    ]
