# Generated by Django 4.2.7 on 2023-11-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_wikipediaarticle_pageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipediaarticle',
            name='pageimage',
            field=models.URLField(default='', max_length=2000, null=True),
        ),
    ]
