# Generated by Django 4.2.7 on 2023-11-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_wikipediaarticle_pageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipediaarticle',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediaarticle',
            name='pageimage',
            field=models.URLField(default='', null=True),
        ),
    ]
