# Generated by Django 4.2.7 on 2023-11-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_wikipediaarticle_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipediaarticle',
            name='coordinates_lat',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediaarticle',
            name='coordinates_lon',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediaarticle',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediaarticle',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wikipediaarticle',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediaarticle',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediaarticle',
            name='ns',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wikipediaarticle',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='wikipediaarticle',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
