# Generated by Django 4.2.7 on 2023-11-09 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_wikipediaarticle_coordinates_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikipediaarticle',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='wikipediaarticle',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='wikipediaarticle',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='wikipediaarticle',
            name='ns',
        ),
        migrations.RemoveField(
            model_name='wikipediaarticle',
            name='pageimage',
        ),
        migrations.RemoveField(
            model_name='wikipediaarticle',
            name='thumbnail',
        ),
    ]
